import { useState, useEffect } from 'react';
import type { Photo, DryRunResult, OperationType } from '@placemark/core';
import { OperationPlanPreview } from './OperationPlanPreview';
import { SourceSummary } from './SourceSummary';
import { TrashAcknowledgeModal, TrashUndoModal } from './TrashModals';
import { useTheme } from '../../hooks/useTheme';
import { formatDateTime, formatBytes } from '../../utils/formatLocale';
import { SPACING, BORDER_RADIUS, FONT_SIZE, FONT_WEIGHT, Z_INDEX } from '../../constants/ui';

interface ExecutionProgress {
  totalFiles: number;
  completedFiles: number;
  currentFile: string;
  percentage: number;
  phase: 'executing' | 'cleanup' | 'complete';
}

interface OperationsPanelProps {
  selectedPhotos: Photo[];
  onClose: () => void;
  onRefreshPhotos: () => Promise<void>;
  toast: {
    success: (message: string) => void;
    error: (message: string) => void;
    info: (message: string) => void;
  };
}

interface BatchInfo {
  id: number;
  operation: OperationType;
  fileCount: number;
  timestamp: number;
}

interface UndoState {
  canUndo: boolean;
  batchInfo?: BatchInfo;
}

export function OperationsPanel({
  selectedPhotos,
  onClose,
  onRefreshPhotos,
  toast,
}: OperationsPanelProps) {
  const { colors, theme } = useTheme();
  const [destPath, setDestPath] = useState<string | null>(null);
  const [opType, setOpType] = useState<OperationType>('copy');
  const [dryRunResult, setDryRunResult] = useState<DryRunResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [executing, setExecuting] = useState(false);
  const [undoState, setUndoState] = useState<UndoState>({ canUndo: false });
  const [progress, setProgress] = useState<ExecutionProgress | null>(null);
  // Incrementing this forces the auto-preview effect to re-run (e.g. after cancel+rollback)
  const [previewVersion, setPreviewVersion] = useState(0);
  // Trash acknowledgement modal: shown when source files were sent to Recycle Bin during execute
  const [trashModal, setTrashModal] = useState<{ count: number } | null>(null);
  // Trash undo modal: shown when undo requires the user to manually restore files from Recycle Bin
  const [trashUndoModal, setTrashUndoModal] = useState<{
    count: number;
    batchId: number;
    wasMoveOp: boolean;
    isDeleteOp: boolean;
  } | null>(null);

  // Check undo availability on mount and after operations
  const checkUndoState = async () => {
    try {
      const state = await window.api.ops.canUndo();
      setUndoState(state);
    } catch (err) {
      // undo state check is non-critical; silently degrade
    }
  };

  useEffect(() => {
    checkUndoState();
  }, []);

  // Auto-generate dry-run preview whenever destination or op type changes.
  // Delete does not need a destination path.
  useEffect(() => {
    if (selectedPhotos.length === 0) {
      setDryRunResult(null);
      setLoading(false);
      return;
    }
    if (opType !== 'delete' && !destPath) {
      setDryRunResult(null);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    const photoIds = selectedPhotos.map((p) => p.id);
    window.api.ops
      .generateDryRun(photoIds, destPath ?? '', opType)
      .then((result) => {
        if (!cancelled) setDryRunResult(result);
      })
      .catch((err: any) => {
        if (!cancelled) {
          toast.error(err.message || 'Failed to generate preview');
          setDryRunResult(null);
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [destPath, opType, previewVersion, selectedPhotos]);

  // Subscribe to progress events while executing
  useEffect(() => {
    if (!executing) {
      setProgress(null);
      return;
    }

    const unsubscribe = window.api.ops.onProgress((p: ExecutionProgress) => {
      setProgress(p);
    });

    return () => {
      unsubscribe?.();
    };
  }, [executing]);

  const handleSelectDest = async () => {
    try {
      const path = await window.api.ops.selectDestination();
      if (path) {
        setDestPath(path);
        // dryRunResult will be cleared & regenerated by the auto-preview effect
      }
    } catch (err) {
      toast.error('Failed to select destination');
    }
  };

  const handleExecute = async () => {
    if (!dryRunResult) return;

    setExecuting(true);
    try {
      const result = await window.api.ops.execute();
      if (result.cancelled) {
        toast.info(result.message);
        // Rollback is complete — force a fresh preview so the UI reflects current filesystem state
        setPreviewVersion((v) => v + 1);
      } else if (opType === 'delete') {
        setDryRunResult(null);
        await checkUndoState();
        await onRefreshPhotos();
        toast.success(result.message);
      } else {
        setDryRunResult(null);
        setDestPath(null); // Reset form so preview clears properly after execution
        await checkUndoState();
        // Refresh photos to get updated paths (important for move operations)
        if (opType === 'move') {
          await onRefreshPhotos();
        }
        // Show acknowledgement modal if source files were trashed (no undo via Placemark)
        if (result.trashedSourceCount && result.trashedSourceCount > 0) {
          setTrashModal({ count: result.trashedSourceCount });
        } else {
          toast.success(result.message);
        }
      }
    } catch (err: any) {
      toast.error(err.message || 'Operation failed');
      // Plan is stale after failure+rollback — force regeneration
      setPreviewVersion((v) => v + 1);
    } finally {
      setExecuting(false);
    }
  };

  const handleCancel = async () => {
    try {
      const result = await window.api.ops.cancel();
      toast.info(result.message);
    } catch (err) {
      toast.error('Failed to cancel operation');
    }
  };

  const handleUndo = async () => {
    try {
      const wasMoveOp = undoState.batchInfo?.operation === 'move';
      const isDeleteOp = undoState.batchInfo?.operation === 'delete';
      const result = await window.api.ops.undo();
      if (result.success) {
        await checkUndoState();
        // Refresh photos for any automatically restored files
        if (wasMoveOp) {
          await onRefreshPhotos();
        }
        if (result.trashedCount && result.trashedCount > 0) {
          // Trashed files need manual Recycle Bin restore — show confirmation modal
          setTrashUndoModal({
            count: result.trashedCount,
            batchId: result.batchId!,
            wasMoveOp,
            isDeleteOp,
          });
        } else {
          toast.success(result.message);
        }
      } else {
        toast.error(result.message);
      }
    } catch (err: any) {
      toast.error(err.message || 'Undo failed');
    }
  };

  const handleConfirmTrashUndo = async () => {
    if (!trashUndoModal) return;
    try {
      await window.api.ops.confirmTrashUndo(trashUndoModal.batchId);
      await checkUndoState();
      if (trashUndoModal.wasMoveOp || trashUndoModal.isDeleteOp) {
        await onRefreshPhotos();
      }
      toast.success('Undo complete.');
    } catch (err: any) {
      toast.error(err.message || 'Failed to confirm undo');
    } finally {
      setTrashUndoModal(null);
    }
  };

  const totalSize = selectedPhotos.reduce((acc, p) => acc + p.fileSize, 0);
  const totalSizeFormatted = formatBytes(totalSize);

  const executeDisabled =
    executing ||
    !dryRunResult ||
    (dryRunResult.operations.filter((op) => op.status === 'pending').length === 0 &&
      dryRunResult.operations.filter((op) => op.status === 'delete-source').length === 0);

  const showDestSection = opType !== 'delete';

  // Styles
  const styles = {
    overlay: {
      position: 'fixed' as const,
      inset: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: Z_INDEX.MODAL,
      padding: SPACING.LG,
      cursor: 'default',
    },
    modal: {
      backgroundColor: colors.surface,
      color: colors.textPrimary,
      borderRadius: BORDER_RADIUS.MD,
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      width: '100%',
      maxWidth: '56rem', // 4xl
      maxHeight: '90vh',
      display: 'flex',
      flexDirection: 'column' as const,
      overflow: 'hidden',
    },
    header: {
      padding: SPACING.LG,
      borderBottom: `1px solid ${colors.border}`,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    content: {
      flex: 1,
      overflow: 'auto',
      padding: SPACING.XL,
      display: 'flex',
      flexDirection: 'column' as const,
      gap: SPACING.XL,
    },
    button: {
      padding: `${SPACING.SM} ${SPACING.LG}`,
      borderRadius: BORDER_RADIUS.SM,
      cursor: 'pointer',
      border: 'none',
    },
    actionBtn: {
      padding: `${SPACING.SM} ${SPACING.XL}`,
      borderRadius: BORDER_RADIUS.SM,
      fontWeight: FONT_WEIGHT.NORMAL,
      color: 'white',
      border: 'none',
      cursor: 'pointer',
    },
  };

  return (
    <div style={styles.overlay} onClick={!executing ? onClose : undefined}>
      <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div style={styles.header}>
          <h2 style={{ margin: 0, fontSize: FONT_SIZE.LG, fontWeight: FONT_WEIGHT.MEDIUM }}>
            File Operations ({selectedPhotos.length} items, {totalSizeFormatted})
          </h2>
          <button
            onClick={!executing ? onClose : undefined}
            style={{
              ...styles.button,
              background: 'none',
              color: colors.textSecondary,
              fontSize: FONT_SIZE.LG,
              cursor: executing ? 'not-allowed' : 'pointer',
              opacity: executing ? 0.4 : 1,
            }}
          >
            ✕
          </button>
        </div>

        {/* Content */}
        <div style={styles.content}>
          {/* Source Summary */}
          <SourceSummary photos={selectedPhotos} />

          {/* Step 1: Configuration */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: SPACING.LG }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: SPACING.LG }}>
              <label style={{ fontWeight: FONT_WEIGHT.NORMAL }}>Operation:</label>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: SPACING.SM,
                  cursor: executing ? 'not-allowed' : 'pointer',
                }}
              >
                <input
                  type="radio"
                  name="opType"
                  checked={opType === 'copy'}
                  onChange={() => setOpType('copy')}
                  disabled={executing}
                />
                <span>Copy</span>
              </label>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: SPACING.SM,
                  cursor: executing ? 'not-allowed' : 'pointer',
                }}
              >
                <input
                  type="radio"
                  name="opType"
                  checked={opType === 'move'}
                  onChange={() => setOpType('move')}
                  disabled={executing}
                />
                <span>Move</span>
              </label>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: SPACING.SM,
                  cursor: executing ? 'not-allowed' : 'pointer',
                }}
              >
                <input
                  type="radio"
                  name="opType"
                  checked={opType === 'delete'}
                  onChange={() => setOpType('delete')}
                  disabled={executing}
                />
                <span style={{ color: opType === 'delete' ? '#ef4444' : undefined }}>Delete</span>
              </label>
            </div>

            {showDestSection && (
              <div style={{ display: 'flex', alignItems: 'center', gap: SPACING.LG }}>
                <button
                  onClick={handleSelectDest}
                  disabled={executing}
                  style={{
                    ...styles.button,
                    backgroundColor: colors.border,
                    color: colors.textPrimary,
                    cursor: executing ? 'not-allowed' : 'pointer',
                    opacity: executing ? 0.5 : 1,
                  }}
                >
                  Select Destination
                </button>
                <div
                  style={{
                    flex: 1,
                    padding: SPACING.SM,
                    backgroundColor: theme === 'dark' ? 'rgba(255,255,255,0.1)' : '#f3f4f6',
                    borderRadius: BORDER_RADIUS.SM,
                    fontFamily: 'monospace',
                    fontSize: FONT_SIZE.SM,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                >
                  {destPath || (
                    <span style={{ color: colors.textMuted, fontStyle: 'italic' }}>
                      No folder selected
                    </span>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Planned operations preview — 3 states */}
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: SPACING.LG,
              borderTop: `1px solid ${colors.border}`,
              paddingTop: SPACING.LG,
            }}
          >
            {!destPath && opType !== 'delete' && (
              <p style={{ color: colors.textMuted, fontStyle: 'italic', margin: 0 }}>
                Select a destination folder to see the planned operations.
              </p>
            )}
            {(destPath || opType === 'delete') && loading && (
              <p style={{ color: colors.textSecondary, margin: 0 }}>Generating preview…</p>
            )}
            {(destPath || opType === 'delete') && !loading && dryRunResult && (
              <OperationPlanPreview result={dryRunResult} colors={colors} />
            )}
            {(destPath || opType === 'delete') && !loading && !dryRunResult && (
              <p style={{ color: '#ef4444', margin: 0, fontSize: FONT_SIZE.SM }}>
                Could not generate preview — check the error notification above.
              </p>
            )}
          </div>

          {/* Progress bar — visible only while executing */}
          {executing && progress && (
            <div
              style={{
                padding: SPACING.MD,
                border: `1px solid ${colors.border}`,
                borderRadius: '6px',
                backgroundColor: theme === 'dark' ? 'rgba(255,255,255,0.04)' : '#f9fafb',
                display: 'flex',
                flexDirection: 'column',
                gap: SPACING.SM,
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ fontWeight: FONT_WEIGHT.MEDIUM }}>Executing…</span>
                <span style={{ color: colors.textSecondary }}>
                  {progress.completedFiles}/{progress.totalFiles} ({progress.percentage}%)
                </span>
              </div>

              {progress.currentFile && (
                <div
                  style={{
                    color: colors.textSecondary,
                    fontFamily: 'monospace',
                    fontSize: FONT_SIZE.SM,
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                  title={progress.currentFile}
                >
                  {progress.currentFile}
                </div>
              )}

              <div
                style={{
                  height: '8px',
                  backgroundColor: colors.borderLight,
                  borderRadius: '999px',
                  overflow: 'hidden',
                }}
              >
                <div
                  style={{
                    width: `${Math.min(100, Math.max(0, progress.percentage))}%`,
                    height: '100%',
                    backgroundColor: colors.primary,
                    transition: 'width 150ms linear',
                  }}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                {progress.phase === 'executing' && (
                  <button
                    onClick={handleCancel}
                    style={{
                      ...styles.button,
                      backgroundColor: '#ef4444',
                      color: 'white',
                    }}
                  >
                    Cancel (Rollback)
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Footer — Execute / Close */}
          <div
            style={{
              display: 'flex',
              justifyContent: 'flex-end',
              alignItems: 'center',
              gap: SPACING.LG,
              paddingTop: SPACING.LG,
              borderTop: `1px solid ${colors.border}`,
            }}
          >
            <button
              onClick={onClose}
              disabled={executing}
              style={{
                ...styles.button,
                backgroundColor: 'transparent',
                border: `1px solid ${colors.border}`,
                cursor: executing ? 'not-allowed' : 'pointer',
                opacity: executing ? 0.5 : 1,
              }}
            >
              Close
            </button>
            <button
              onClick={handleExecute}
              disabled={executeDisabled}
              style={{
                ...styles.actionBtn,
                backgroundColor: executeDisabled
                  ? colors.textMuted
                  : opType === 'delete'
                    ? '#ef4444'
                    : '#22c55e',
                cursor: executeDisabled ? 'not-allowed' : 'pointer',
              }}
            >
              {executing
                ? 'Executing…'
                : opType === 'copy'
                  ? 'Execute Copy'
                  : opType === 'move'
                    ? 'Execute Move'
                    : `Delete ${selectedPhotos.length} file${selectedPhotos.length !== 1 ? 's' : ''}`}
            </button>
          </div>

          {/* Undo Section - visible when batch undo is available */}
          {undoState.canUndo && undoState.batchInfo && (
            <div
              style={{
                borderTop: `1px solid ${colors.border}`,
                paddingTop: SPACING.LG,
                marginTop: SPACING.SM,
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: SPACING.MD,
                  backgroundColor: theme === 'dark' ? 'rgba(255, 193, 7, 0.1)' : '#fef3c7',
                  borderRadius: '6px',
                  border: `1px solid ${theme === 'dark' ? 'rgba(255, 193, 7, 0.3)' : '#fcd34d'}`,
                }}
              >
                <div style={{ display: 'flex', flexDirection: 'column', gap: SPACING.XS }}>
                  <span style={{ fontWeight: FONT_WEIGHT.NORMAL, fontSize: FONT_SIZE.SM }}>
                    Last operation: {undoState.batchInfo.operation} ({undoState.batchInfo.fileCount}{' '}
                    files)
                  </span>
                  <span style={{ fontSize: FONT_SIZE.XS, color: colors.textSecondary }}>
                    {formatDateTime(undoState.batchInfo.timestamp)}
                  </span>
                </div>
                <button
                  onClick={handleUndo}
                  disabled={executing}
                  style={{
                    ...styles.actionBtn,
                    backgroundColor: executing ? colors.textMuted : '#f59e0b',
                    fontSize: FONT_SIZE.SM,
                    padding: `${SPACING.XS} ${SPACING.LG}`,
                    cursor: executing ? 'not-allowed' : 'pointer',
                  }}
                >
                  Undo Batch
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Recycle Bin acknowledgement modal */}
      {trashModal && (
        <TrashAcknowledgeModal
          count={trashModal.count}
          colors={colors}
          actionBtnStyle={styles.actionBtn}
          onClose={() => setTrashModal(null)}
        />
      )}

      {/* Trash undo modal — shown when undo involves files that were sent to the Recycle Bin */}
      {trashUndoModal && (
        <TrashUndoModal
          count={trashUndoModal.count}
          isDeleteOp={trashUndoModal.isDeleteOp}
          colors={colors}
          buttonStyle={styles.button}
          actionBtnStyle={styles.actionBtn}
          onCancel={() => setTrashUndoModal(null)}
          onConfirm={handleConfirmTrashUndo}
        />
      )}
    </div>
  );
}
