import { useState, useEffect } from 'react';
import type { Photo, DryRunResult, OperationType } from '@placemark/core';
import { DryRunPreview } from './DryRunPreview';
import { SourceSummary } from './SourceSummary';
import { useTheme } from '../../hooks/useTheme';
import { formatDateTime } from '../../utils/formatLocale';

interface ExecutionProgress {
  totalFiles: number;
  completedFiles: number;
  currentFile: string;
  percentage: number;
  phase: 'executing' | 'complete';
}

interface OperationsPanelProps {
  selectedPhotos: Photo[];
  onClose: () => void;
  onRefreshPhotos: () => Promise<void>;
  toast: {
    success: (message: string) => void;
    error: (message: string) => void;
    info: (message: string) => void;
  };
}

interface BatchInfo {
  id: number;
  operation: OperationType;
  fileCount: number;
  timestamp: number;
}

interface UndoState {
  canUndo: boolean;
  batchInfo?: BatchInfo;
}

export function OperationsPanel({
  selectedPhotos,
  onClose,
  onRefreshPhotos,
  toast,
}: OperationsPanelProps) {
  const { colors, theme } = useTheme();
  const [destPath, setDestPath] = useState<string | null>(null);
  const [opType, setOpType] = useState<OperationType>('copy');
  const [dryRunResult, setDryRunResult] = useState<DryRunResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [executing, setExecuting] = useState(false);
  const [undoState, setUndoState] = useState<UndoState>({ canUndo: false });
  const [progress, setProgress] = useState<ExecutionProgress | null>(null);
  // Incrementing this forces the auto-preview effect to re-run (e.g. after cancel+rollback)
  const [previewVersion, setPreviewVersion] = useState(0);

  // Check undo availability on mount and after operations
  const checkUndoState = async () => {
    try {
      const state = await window.api.ops.canUndo();
      setUndoState(state);
    } catch (err) {
      // undo state check is non-critical; silently degrade
    }
  };

  useEffect(() => {
    checkUndoState();
  }, []);

  // Auto-generate dry-run preview whenever destination or op type changes
  useEffect(() => {
    if (!destPath || selectedPhotos.length === 0) {
      setDryRunResult(null);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    const photoIds = selectedPhotos.map((p) => p.id);
    window.api.ops
      .generateDryRun(photoIds, destPath, opType)
      .then((result) => {
        if (!cancelled) setDryRunResult(result);
      })
      .catch((err: any) => {
        if (!cancelled) {
          toast.error(err.message || 'Failed to generate preview');
          setDryRunResult(null);
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [destPath, opType, previewVersion, selectedPhotos]);

  // Subscribe to progress events while executing
  useEffect(() => {
    if (!executing) {
      setProgress(null);
      return;
    }

    const unsubscribe = window.api.ops.onProgress((p: ExecutionProgress) => {
      setProgress(p);
    });

    return () => {
      unsubscribe?.();
    };
  }, [executing]);

  const handleSelectDest = async () => {
    try {
      const path = await window.api.ops.selectDestination();
      if (path) {
        setDestPath(path);
        // dryRunResult will be cleared & regenerated by the auto-preview effect
      }
    } catch (err) {
      toast.error('Failed to select destination');
    }
  };

  const handleExecute = async () => {
    if (!dryRunResult) return;

    setExecuting(true);
    try {
      const result = await window.api.ops.execute();
      if ((result as any).cancelled) {
        toast.info(result.message);
        // Rollback is complete — force a fresh preview so the UI reflects current filesystem state
        setPreviewVersion((v) => v + 1);
      } else {
        toast.success(result.message);
        setDryRunResult(null);
        setDestPath(null); // Reset form so preview clears properly after execution
        await checkUndoState();
        // Refresh photos to get updated paths (important for move operations)
        if (opType === 'move') {
          await onRefreshPhotos();
        }
      }
    } catch (err: any) {
      toast.error(err.message || 'Operation failed');
      // Plan is stale after failure+rollback — force regeneration
      setPreviewVersion((v) => v + 1);
    } finally {
      setExecuting(false);
    }
  };

  const handleCancel = async () => {
    try {
      const result = await window.api.ops.cancel();
      toast.info(result.message);
    } catch (err) {
      toast.error('Failed to cancel operation');
    }
  };

  const handleUndo = async () => {
    try {
      const wasMoveOp = undoState.batchInfo?.operation === 'move';
      const result = await window.api.ops.undo();
      if (result.success) {
        toast.success(result.message);
        await checkUndoState();
        // Refresh photos to restore original paths (for move undo)
        if (wasMoveOp) {
          await onRefreshPhotos();
        }
      } else {
        toast.error(result.message);
      }
    } catch (err: any) {
      toast.error(err.message || 'Undo failed');
    }
  };

  const totalSize = selectedPhotos.reduce((acc, p) => acc + p.fileSize, 0);
  const totalSizeMB = (totalSize / (1024 * 1024)).toFixed(1);

  const executeDisabled =
    executing ||
    !dryRunResult ||
    dryRunResult.operations.filter((op) => op.status === 'pending').length === 0;

  // Styles
  const styles = {
    overlay: {
      position: 'fixed' as const,
      inset: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 50,
      padding: '1rem',
      cursor: 'default',
    },
    modal: {
      backgroundColor: colors.surface,
      color: colors.textPrimary,
      borderRadius: '8px',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      width: '100%',
      maxWidth: '56rem', // 4xl
      maxHeight: '90vh',
      display: 'flex',
      flexDirection: 'column' as const,
      overflow: 'hidden',
    },
    header: {
      padding: '1rem',
      borderBottom: `1px solid ${colors.border}`,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    content: {
      flex: 1,
      overflow: 'auto',
      padding: '1.5rem',
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '1.5rem',
    },
    button: {
      padding: '0.5rem 1rem',
      borderRadius: '4px',
      cursor: 'pointer',
      border: 'none',
    },
    actionBtn: {
      padding: '0.5rem 1.5rem',
      borderRadius: '4px',
      fontWeight: 500,
      color: 'white',
      border: 'none',
      cursor: 'pointer',
    },
  };

  return (
    <div style={styles.overlay} onClick={!executing ? onClose : undefined}>
      <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div style={styles.header}>
          <h2 style={{ margin: 0, fontSize: '1.25rem', fontWeight: 600 }}>
            File Operations ({selectedPhotos.length} items, {totalSizeMB} MB)
          </h2>
          <button
            onClick={!executing ? onClose : undefined}
            style={{
              ...styles.button,
              background: 'none',
              color: colors.textSecondary,
              fontSize: '1.25rem',
              cursor: executing ? 'not-allowed' : 'pointer',
              opacity: executing ? 0.4 : 1,
            }}
          >
            ✕
          </button>
        </div>

        {/* Content */}
        <div style={styles.content}>
          {/* Source Summary */}
          <SourceSummary photos={selectedPhotos} />

          {/* Step 1: Configuration */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <label style={{ fontWeight: 500 }}>Operation:</label>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  cursor: executing ? 'not-allowed' : 'pointer',
                }}
              >
                <input
                  type="radio"
                  name="opType"
                  checked={opType === 'copy'}
                  onChange={() => setOpType('copy')}
                  disabled={executing}
                />
                <span>Copy</span>
              </label>
              <label
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.5rem',
                  cursor: executing ? 'not-allowed' : 'pointer',
                }}
              >
                <input
                  type="radio"
                  name="opType"
                  checked={opType === 'move'}
                  onChange={() => setOpType('move')}
                  disabled={executing}
                />
                <span>Move</span>
              </label>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <button
                onClick={handleSelectDest}
                disabled={executing}
                style={{
                  ...styles.button,
                  backgroundColor: colors.border,
                  color: colors.textPrimary,
                  cursor: executing ? 'not-allowed' : 'pointer',
                  opacity: executing ? 0.5 : 1,
                }}
              >
                Select Destination
              </button>
              <div
                style={{
                  flex: 1,
                  padding: '0.5rem',
                  backgroundColor: theme === 'dark' ? 'rgba(255,255,255,0.1)' : '#f3f4f6',
                  borderRadius: '4px',
                  fontFamily: 'monospace',
                  fontSize: '0.875rem',
                  overflow: 'hidden',
                  textOverflow: 'ellipsis',
                  whiteSpace: 'nowrap',
                }}
              >
                {destPath || (
                  <span style={{ color: colors.textMuted, fontStyle: 'italic' }}>
                    No folder selected
                  </span>
                )}
              </div>
            </div>
          </div>

          {/* Planned operations preview — 3 states */}
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '1rem',
              borderTop: `1px solid ${colors.border}`,
              paddingTop: '1rem',
            }}
          >
            {!destPath && (
              <p style={{ color: colors.textMuted, fontStyle: 'italic', margin: 0 }}>
                Select a destination folder to see the planned operations.
              </p>
            )}
            {destPath && loading && (
              <p style={{ color: colors.textSecondary, margin: 0 }}>Generating preview…</p>
            )}
            {destPath && !loading && dryRunResult && (
              <DryRunPreview result={dryRunResult} colors={colors} />
            )}
            {destPath && !loading && !dryRunResult && (
              <p style={{ color: '#ef4444', margin: 0, fontSize: '0.875rem' }}>
                Could not generate preview — check the error notification above.
              </p>
            )}
          </div>

          {/* Progress bar — visible only while executing */}
          {executing && progress && (
            <div
              style={{
                padding: '0.75rem',
                border: `1px solid ${colors.border}`,
                borderRadius: '6px',
                backgroundColor: theme === 'dark' ? 'rgba(255,255,255,0.04)' : '#f9fafb',
                display: 'flex',
                flexDirection: 'column',
                gap: '0.5rem',
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <span style={{ fontWeight: 600 }}>Executing…</span>
                <span style={{ color: colors.textSecondary }}>
                  {progress.completedFiles}/{progress.totalFiles} ({progress.percentage}%)
                </span>
              </div>

              {progress.currentFile && (
                <div
                  style={{
                    color: colors.textSecondary,
                    fontFamily: 'monospace',
                    fontSize: '0.8rem',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                  }}
                  title={progress.currentFile}
                >
                  {progress.currentFile}
                </div>
              )}

              <div
                style={{
                  height: '8px',
                  backgroundColor: colors.borderLight,
                  borderRadius: '999px',
                  overflow: 'hidden',
                }}
              >
                <div
                  style={{
                    width: `${Math.min(100, Math.max(0, progress.percentage))}%`,
                    height: '100%',
                    backgroundColor: colors.primary,
                    transition: 'width 150ms linear',
                  }}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <button
                  onClick={handleCancel}
                  style={{
                    ...styles.button,
                    backgroundColor: '#ef4444',
                    color: 'white',
                  }}
                >
                  Cancel (Rollback)
                </button>
              </div>
            </div>
          )}

          {/* Footer — Execute / Close */}
          <div
            style={{
              display: 'flex',
              justifyContent: 'flex-end',
              alignItems: 'center',
              gap: '1rem',
              paddingTop: '1rem',
              borderTop: `1px solid ${colors.border}`,
            }}
          >
            <button
              onClick={onClose}
              disabled={executing}
              style={{
                ...styles.button,
                backgroundColor: 'transparent',
                border: `1px solid ${colors.border}`,
                cursor: executing ? 'not-allowed' : 'pointer',
                opacity: executing ? 0.5 : 1,
              }}
            >
              Close
            </button>
            <button
              onClick={handleExecute}
              disabled={executeDisabled}
              style={{
                ...styles.actionBtn,
                backgroundColor: executeDisabled ? colors.textMuted : '#22c55e',
                cursor: executeDisabled ? 'not-allowed' : 'pointer',
              }}
            >
              {executing ? 'Executing…' : `Execute ${opType === 'copy' ? 'Copy' : 'Move'}`}
            </button>
          </div>

          {/* Undo Section - visible when batch undo is available */}
          {undoState.canUndo && undoState.batchInfo && (
            <div
              style={{
                borderTop: `1px solid ${colors.border}`,
                paddingTop: '1rem',
                marginTop: '0.5rem',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: '0.75rem',
                  backgroundColor: theme === 'dark' ? 'rgba(255, 193, 7, 0.1)' : '#fef3c7',
                  borderRadius: '6px',
                  border: `1px solid ${theme === 'dark' ? 'rgba(255, 193, 7, 0.3)' : '#fcd34d'}`,
                }}
              >
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                  <span style={{ fontWeight: 500, fontSize: '0.875rem' }}>
                    Last operation: {undoState.batchInfo.operation} ({undoState.batchInfo.fileCount}{' '}
                    files)
                  </span>
                  <span style={{ fontSize: '0.75rem', color: colors.textSecondary }}>
                    {formatDateTime(undoState.batchInfo.timestamp)}
                  </span>
                </div>
                <button
                  onClick={handleUndo}
                  disabled={executing}
                  style={{
                    ...styles.actionBtn,
                    backgroundColor: executing ? colors.textMuted : '#f59e0b',
                    fontSize: '0.875rem',
                    padding: '0.4rem 1rem',
                    cursor: executing ? 'not-allowed' : 'pointer',
                  }}
                >
                  Undo Batch
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
