packages:
  - packages/*

ignoredBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild

onlyBuiltDependencies:
  - sharp

overrides:
  '@electron/rebuild': ^4.0.2
  esbuild: ^0.25.0
  tar: ^7.4.3
