packages:
  - packages/*

# Only ignore dev-time tools that don't ship to production
# better-sqlite3 must be rebuilt for Electron's Node ABI
ignoredBuiltDependencies:
  - esbuild
  - electron
  - electron-winstaller
